# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 20:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20170808_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON string containing Custom backend settings.', verbose_name='Custom settings'),
        ),
    ]
