# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-09 10:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20170808_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_billing_information',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
