# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-09 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_stripe_billing_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_billing_information',
            new_name='meta_data',
        ),
    ]
