# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-19 21:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_businessclient_enterprise_customer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON string containing Custom backend settings.', verbose_name='Custom settings'),
        ),
    ]
