# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180119_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_subscription',
            field=models.BooleanField(default=0),
        ),
    ]
