# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plan_name',
            field=models.CharField(default='test-edx-integration', max_length=255),
        ),
    ]
