# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='plan_name',
            new_name='subscription_plan_name',
        ),
    ]
