# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180406_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscription_plan_name',
            field=models.CharField(default='test-edx-integration', max_length=255, null=True),
        ),
    ]
