# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180406_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscription_plan_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
